name: PR Moderation

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - assigned
      - unassigned
      - labeled
      - unlabeled

jobs:
  verify:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'WIP') }}
    name: Verify PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Checkout repo..."
        uses: actions/checkout@v3

      - name: "Install core dependencies"
        run: npm install @actions/core
      
      - name: "Install actions dependencies"
        run: npm install @actions/github

      - name: "Check PR Description"
        uses: ./.github/actions/check-pr-desc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: "Check PR Assignee"
        uses: ./.github/actions/check-pr-assignee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Check tasklist
        uses: Awayume/github-pr-tasklist-checker@v1
